services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - mp-network
    volumes:
      - mp_sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./mp-backend
    container_name: mp-backend
    depends_on:
      - sqlserver
    ports:
      - "3001:3001"
    networks:
      - mp-network
    volumes:
      - ./mp-backend:/usr/src/app
    environment:
      - NODE_ENV=production
      # Si usas variables de config, añade aquí FRONTEND_URL, etc.

  frontend:
    build:
      context: ./mp-frontend
    container_name: mp-frontend
    depends_on:
      - backend
    ports:
      - "80:80" # Así accedes a frontend por http://midominio.local
    networks:
      - mp-network
    environment:
      - NODE_ENV=production
      # Si usas variables de config, añade aquí VITE_API_URL, etc.

networks:
  mp-network:
    driver: bridge

volumes:
  mp_sqlserver_data:
    external: true